spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
  security:
    oauth2:
      resourceserver:
        opaque-token:
          client-id: unknown
          client-secret: unknown
          introspection-uri: unknown
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - env
