name: Push a Release Image to Amazon ECR

on:
  release:
    types:
      - published

env:
  DOCKER_REGISTRY: 650504438179.dkr.ecr.ap-northeast-2.amazonaws.com
  IMAGE_NAME: ${{ github.repository }}:${{ github.event.release.name }}

jobs:
  login-to-amazon-ecr:
    name: Login to Amazon ECR Private
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::650504438179:role/GitHubOIDCAssumingRole
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

    outputs:
      username: ${{ steps.login-ecr.outputs.docker_username_650504438179_dkr_ecr_ap_northeast_2_amazonaws_com }}
      password: ${{ steps.login-ecr.outputs.docker_password_650504438179_dkr_ecr_ap_northeast_2_amazonaws_com }}

  push-image-to-amazon-ecr:
    name: Push an Image to Amazon ECR
    needs: login-to-amazon-ecr
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build and push image to Amazon ECR
        uses: gradle/gradle-build-action@v2
        env:
          IMAGE_NAME: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}
          DOCKER_REGISTRY: ${{ env.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ needs.login-to-amazon-ecr.outputs.username }}
          DOCKER_PASSWORD: ${{ needs.login-to-amazon-ecr.outputs.password }}
        with:
          arguments: bootBuildImage --publishImage
